services:
  - docker

before_script:
- docker-compose up couchdb -d
- while [ $? -ne 0 ]; do sleep 1 && curl -v http://localhost:5984; done

script:
  - docker-compose run couchjs lint
  - docker-compose run couchdjs test
